CREATE TABLE BRANDS(
   BRAND_ID               VARCHAR2 (255),
   BRAND_NAME             VARCHAR2 (255),
   BRANDPARENT_CATEGORY   VARCHAR2 (255),
   LOGO_IMAGE_URL         VARCHAR2 (255),
   OVERLAY_IMAGE_URL      VARCHAR2 (255),
   STATUS                 NUMBER,
   IMAGE_URL              VARCHAR2 (255),
   MOBILE_LOGO_IMAGE      VARCHAR2 (255));

  CREATE TABLE BRANDPRDREL(
   BRAND_ID     VARCHAR2 (255),
   LISTING_ID   VARCHAR2 (255),
   STATUS       NUMBER (10, 2)) ;
    
   CREATE TABLE CATEGORY(
   CATEGORY_ID       VARCHAR2 (255),
   CATEGORY_NAME     VARCHAR2 (255),
   PARENT_CATEGORY   VARCHAR2 (255),
   LOGO_URL          VARCHAR2 (255),
   IMAGE_URL         VARCHAR2 (255),
   STATUS            NUMBER);
   
   
   CREATE TABLE CATPRDREL(
   CATEGORY_ID   VARCHAR2 (255),
   LISTING_ID    VARCHAR2 (255),
   STATUS        NUMBER (10, 2));
   
   CREATE TABLE COLLECTION(
   COLLECTION_ID            VARCHAR2 (255),
   COLLECTION_NAME          VARCHAR2 (255),
   COLLECTION_CATEGORY      VARCHAR2 (4000),
   PRODUCT_COLLECTION       VARCHAR2 (4000),
   START_DATE               TIMESTAMP (6),
   END_DATE                 TIMESTAMP (6),
   TARGET_GROUP             VARCHAR2 (255),
   OCCASION                 VARCHAR2 (255),
   TOP_LEFT_IMAGE_URL       VARCHAR2 (1000),
   TOP_RIGHT_IMAGE_URL      VARCHAR2 (1000),
   BOTTOM_LEFT_IMAGE_URL    VARCHAR2 (1000),
   BOTTOM_RIGHT_IMAGE_URL   VARCHAR2 (1000),
   STATUS                   NUMBER,
   MOBILE_IMAGE             VARCHAR2 (1000),
   GENDER                   VARCHAR2 (20));

CREATE TABLE PRICE_INVENTORY(
   SITE_USS_ID        VARCHAR2 (255),
   LISTING_ID         VARCHAR2 (255),
   ORIGINAL_PRICE     NUMBER (10),
   PRICE              NUMBER (10),
   DISCOUNTED_PRICE   NUMBER (10),
   INVENTORY          NUMBER (10),
   WEIGHTAGE          FLOAT (126),
   STATUS             NUMBER (10),
   SELLERID           VARCHAR2 (255),
   SELLERNAME         VARCHAR2 (255),
   DELISTED           NUMBER (10),
   ONLINEEXCLUSIVE    NUMBER (10),
   ISCREATED          NUMBER );
   
   
   
   
   
