//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.06 at 12:22:17 PM IST
//


package com.tisl.mpl.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TPLCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AWBRequestInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AWBNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "tplCode", "awbRequestInfo" })
@XmlRootElement(name = "AWBStatusRequest")
public class AWBStatusRequest implements java.io.Serializable
{

	@XmlElement(name = "TPLCode", required = true)
	private String tplCode;
	@XmlElement(name = "AWBRequestInfo", required = true)
	private AWBStatusRequest.AWBRequestInfo awbRequestInfo;

	/**
	 * Gets the value of the tplCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTPLCode()
	{
		return tplCode;
	}

	/**
	 * Sets the value of the tplCode property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setTPLCode(final String value)
	{
		this.tplCode = value;
	}

	/**
	 * Gets the value of the awbRequestInfo property.
	 *
	 * @return possible object is {@link AWBStatusRequest.AWBRequestInfo }
	 *
	 */
	public AWBStatusRequest.AWBRequestInfo getAWBRequestInfo()
	{
		return awbRequestInfo;
	}

	/**
	 * Sets the value of the awbRequestInfo property.
	 *
	 * @param value
	 *           allowed object is {@link AWBStatusRequest.AWBRequestInfo }
	 *
	 */
	public void setAWBRequestInfo(final AWBStatusRequest.AWBRequestInfo value)
	{
		this.awbRequestInfo = value;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="AWBNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "awbNumber" })
	public static class AWBRequestInfo
	{

		@XmlElement(name = "AWBNumber", required = true)
		private String awbNumber;

		/**
		 * Gets the value of the awbNumber property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getAWBNumber()
		{
			return awbNumber;
		}

		/**
		 * Sets the value of the awbNumber property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setAWBNumber(final String value)
		{
			this.awbNumber = value;
		}

	}

}
