//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.02 at 01:52:26 PM IST
//


package com.tisl.mpl.xml.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AWBResponseInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AWBNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ShipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="StatusRecords" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *                             &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Error" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "awbResponseInfo", "error" })
@XmlRootElement(name = "AWBStatusResponse")
public class AWBStatusResponse implements java.io.Serializable
{

	@XmlElement(name = "AWBResponseInfo")
	private List<AWBStatusResponse.AWBResponseInfo> awbResponseInfo;
	@XmlElement(name = "Error")
	private List<AWBStatusResponse.Error> error;

	/**
	 * Gets the value of the awbResponseInfo property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the awbResponseInfo property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getAWBResponseInfo().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AWBStatusResponse.AWBResponseInfo }
	 *
	 *
	 */
	public List<AWBStatusResponse.AWBResponseInfo> getAWBResponseInfo()
	{
		if (awbResponseInfo == null)
		{
			awbResponseInfo = new ArrayList<AWBStatusResponse.AWBResponseInfo>();
		}
		return this.awbResponseInfo;
	}

	/**
	 * Gets the value of the error property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the error property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getError().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AWBStatusResponse.Error }
	 *
	 *
	 */
	public List<AWBStatusResponse.Error> getError()
	{
		if (error == null)
		{
			error = new ArrayList<AWBStatusResponse.Error>();
		}
		return this.error;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="AWBNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="ShipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="StatusRecords" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
	 *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
	 *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "awbNumber", "shipmentStatus", "responseCode", "statusRecords" })
	public static class AWBResponseInfo
	{

		@XmlElement(name = "AWBNumber")
		private String awbNumber;
		@XmlElement(name = "ShipmentStatus")
		private String shipmentStatus;
		@XmlElement(name = "ResponseCode")
		private String responseCode;
		@XmlElement(name = "StatusRecords")
		private List<AWBStatusResponse.AWBResponseInfo.StatusRecords> statusRecords;

		/**
		 * Gets the value of the awbNumber property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getAWBNumber()
		{
			return awbNumber;
		}

		/**
		 * Sets the value of the awbNumber property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setAWBNumber(final String value)
		{
			this.awbNumber = value;
		}

		/**
		 * Gets the value of the shipmentStatus property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShipmentStatus()
		{
			return shipmentStatus;
		}

		/**
		 * Sets the value of the shipmentStatus property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShipmentStatus(final String value)
		{
			this.shipmentStatus = value;
		}

		/**
		 * Gets the value of the responseCode property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getResponseCode()
		{
			return responseCode;
		}

		/**
		 * Sets the value of the responseCode property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setResponseCode(final String value)
		{
			this.responseCode = value;
		}

		/**
		 * Gets the value of the statusRecords property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
		 * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the statusRecords property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getStatusRecords().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link AWBStatusResponse.AWBResponseInfo.StatusRecords }
		 *
		 *
		 */
		public List<AWBStatusResponse.AWBResponseInfo.StatusRecords> getStatusRecords()
		{
			if (statusRecords == null)
			{
				statusRecords = new ArrayList<AWBStatusResponse.AWBResponseInfo.StatusRecords>();
			}
			return this.statusRecords;
		}


		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
		 *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
		 *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder =
		{ "date", "time", "location", "statusDescription" })
		public static class StatusRecords
		{

			@XmlElement(name = "Date")
			@XmlSchemaType(name = "date")
			private String date;
			@XmlElement(name = "Time")
			@XmlSchemaType(name = "time")
			private String time;
			@XmlElement(name = "Location")
			private String location;
			@XmlElement(name = "StatusDescription")
			private String statusDescription;

			/**
			 * Gets the value of the date property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getDate()
			{
				return date;
			}

			/**
			 * Sets the value of the date property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setDate(final String value)
			{
				this.date = value;
			}

			/**
			 * Gets the value of the time property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getTime()
			{
				return time;
			}

			/**
			 * Sets the value of the time property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setTime(final String value)
			{
				this.time = value;
			}

			/**
			 * Gets the value of the location property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getLocation()
			{
				return location;
			}

			/**
			 * Sets the value of the location property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setLocation(final String value)
			{
				this.location = value;
			}

			/**
			 * Gets the value of the statusDescription property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getStatusDescription()
			{
				return statusDescription;
			}

			/**
			 * Sets the value of the statusDescription property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setStatusDescription(final String value)
			{
				this.statusDescription = value;
			}

		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "message" })
	public static class Error
	{

		@XmlElement(name = "Message")
		private String message;

		/**
		 * Gets the value of the message property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getMessage()
		{
			return message;
		}

		/**
		 * Sets the value of the message property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setMessage(final String value)
		{
			this.message = value;
		}

	}

}
