//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.22 at 12:31:51 PM IST
//


package com.tisl.mpl.xml.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>
 * Java class for isCancellableResponse element declaration.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="isCancellableResponse">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="OrderLine" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}string"/>								--Order Reference Number
 *                     &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>						--Transaction ID
 *                     &lt;element name="isCancellable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 	--Y/N
 *                     &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>			--If failed reason remarks
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 * --Cancel is done for all order lines or none. But response is sent with remarks where cancel status is failed --For
 * return and refund, isCancellable and remarks are not populated.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "orderLine" })
@XmlRootElement(name = "isCancellableResponse")
public class MplOrderIsCancellableResponse
{

	@XmlElement(name = "OrderLine", required = true)
	protected List<OrderLine> orderLine;

	/**
	 * Gets the value of the orderLine property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the orderLine property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getOrderLine().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OrderLine }
	 *
	 *
	 */
	public List<OrderLine> getOrderLine()
	{
		if (orderLine == null)
		{
			orderLine = new ArrayList<OrderLine>();
		}
		return this.orderLine;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="isCancellable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
	 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "orderId", "transactionId", "isCancellable", "remarks" })
	public static class OrderLine
	{

		@XmlElement(required = true)
		protected String orderId;
		@XmlElement(required = true)
		protected String transactionId;
		protected String isCancellable;
		protected String remarks;

		/**
		 * Gets the value of the orderId property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderId()
		{
			return orderId;
		}

		/**
		 * Sets the value of the orderId property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderId(final String value)
		{
			this.orderId = value;
		}

		/**
		 * Gets the value of the transactionId property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getTransactionId()
		{
			return transactionId;
		}



		/**
		 * Sets the value of the transactionId property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setTransactionId(final String value)
		{
			this.transactionId = value;
		}

		/**
		 * Gets the value of the isCancellable property.
		 *
		 * @return possible object is {@link Boolean }
		 *
		 */
		public String isIsCancellable()
		{
			return isCancellable;
		}

		/**
		 * Sets the value of the isCancellable property.
		 *
		 * @param value
		 *           allowed object is {@link Boolean }
		 *
		 */
		public void setIsCancellable(final String value)
		{
			this.isCancellable = value;
		}

		/**
		 * Gets the value of the remarks property.
		 *
		 * @return possible object is {@link Boolean }
		 *
		 */
		public String isRemarks()
		{
			return remarks;
		}

		/**
		 * Sets the value of the remarks property.
		 *
		 * @param value
		 *           allowed object is {@link Boolean }
		 *
		 */
		public void setRemarks(final String value)
		{
			this.remarks = value;
		}

	}

}
