

package marketplacecoupon;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"CouponMailJob",
			"CronJob",
			com.tisl.mpl.jalo.CouponMailJob.class,
			null,
			false,
			null,
			false
		);
	
		createEnumerationType(
			"eventTypeEnum",
			null
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_CouponMailJob_voucherCode();
			
				single_createattr_CouponMailJob_targetCustomer();
			
				single_createattr_VoucherInvalidation_savedAmount();
			
				single_createattr_Voucher_maxDiscountValue();
			
				single_createattr_ProductRestriction_productCodeList();
			

	}

	
	public void single_createattr_CouponMailJob_voucherCode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CouponMailJob", 
					"voucherCode",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CouponMailJob_targetCustomer() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CouponMailJob", 
					"targetCustomer",  
					null,
					"PrincipalCollection",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_VoucherInvalidation_savedAmount() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"VoucherInvalidation", 
					"savedAmount",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Voucher_maxDiscountValue() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Voucher", 
					"maxDiscountValue",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ProductRestriction_productCodeList() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ProductRestriction", 
					"productCodeList",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"eventTypeEnum",
			false,
			Arrays.asList( new String[] {
			
				"anniversary",
				"birthday",
				"purchaseAmount",
				"firstTimeReg",
				"cartNotShopped",
				"cartAbanPmtPage",
				"cartAbanCartPage"
			} )
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CouponMailJob",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CouponMailJob_voucherCode();
		
			single_setAttributeProperties_CouponMailJob_targetCustomer();
		
				{
				Map customPropsMap = new HashMap();
				
				changeMetaType(
					"VoucherInvalidation",
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_VoucherInvalidation_savedAmount();
		
				{
				Map customPropsMap = new HashMap();
				
				changeMetaType(
					"Voucher",
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_Voucher_maxDiscountValue();
		
				{
				Map customPropsMap = new HashMap();
				
				changeMetaType(
					"ProductRestriction",
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_ProductRestriction_productCodeList();
		
				setDefaultProperties(
					"eventTypeEnum",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_CouponMailJob_voucherCode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CouponMailJob", 
								"voucherCode",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CouponMailJob_targetCustomer() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CouponMailJob", 
								"targetCustomer",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_VoucherInvalidation_savedAmount() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
								customPropsMap.put( "hmcIndexField", "thefield" );
							
							setAttributeProperties(
								"VoucherInvalidation", 
								"savedAmount",
								false, 
								Double.valueOf(0.0D),
								"Double.valueOf(0.0D)",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Voucher_maxDiscountValue() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
								customPropsMap.put( "hmcIndexField", "thefield" );
							
							setAttributeProperties(
								"Voucher", 
								"maxDiscountValue",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ProductRestriction_productCodeList() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ProductRestriction", 
								"productCodeList",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
}

	